from decouple import config


OPENAI_API_KEY = config('OPENAI_API_KEY')
ASSISTANT_MODEL = config('ASSISTANT_MODEL')
ASSISTANT_ID = config('ASSISTANT_ID')

GOOGLE_CREDENTIALS = config('GOOGLE_CREDENTIALS')
SPREADSHEET_ID = config('SPREADSHEET_ID')
